#!/usr/bin/env bash
# clean.sh — remove data files generated by the spatial_transcriptomics series
#
# Usage:
#   ./clean.sh            # dry run: show what would be deleted
#   ./clean.sh --force    # actually delete the files
#
# All files listed here can be fully regenerated by re-running the notebooks.
# The underlying Visium and seqFISH+ datasets are fetched automatically via
# sq.datasets.* and cached by squidpy (not listed here).

set -euo pipefail

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

DATA_DIR="$(cd "$(dirname "$0")/../data" 2>/dev/null && pwd)" || {
  echo "data/ directory not found — nothing to clean."
  exit 0
}

# Files written by SP00–SP04 to ../data/
FILES=(
  "$DATA_DIR/visium_processed.h5ad"   # SP01 → used by SP02, SP04
  "$DATA_DIR/visium_sdata.zarr"       # SP00 (Zarr directory store)
)

FOUND=()
for f in "${FILES[@]}"; do
  if [[ -e "$f" ]]; then
    FOUND+=("$f")
  fi
done

if [[ ${#FOUND[@]} -eq 0 ]]; then
  echo "Nothing to clean — no spatial_transcriptomics data files found in $DATA_DIR"
  exit 0
fi

echo "spatial_transcriptomics data files to remove:"
TOTAL=0
for f in "${FOUND[@]}"; do
  SIZE=$(du -sh "$f" 2>/dev/null | cut -f1)
  echo "  [$SIZE]  $f"
  BYTES=$(du -sk "$f" 2>/dev/null | cut -f1)
  TOTAL=$((TOTAL + BYTES))
done
echo "  Total: $(echo "$TOTAL" | awk '{printf "%.1f MB", $1/1024}') would be freed"

if [[ "$FORCE" == false ]]; then
  echo ""
  echo "Dry run — no files deleted. Run with --force to delete."
  exit 0
fi

echo ""
for f in "${FOUND[@]}"; do
  rm -rf "$f"
  echo "Deleted: $f"
done
echo "Done."
