#!/usr/bin/env bash
# clean.sh — remove data files generated by the perturb_seq series
#
# Usage:
#   ./clean.sh            # dry run: show what would be deleted
#   ./clean.sh --force    # actually delete the files
#
# All files listed here can be fully regenerated by re-running the notebooks.
# Raw downloads (norman2019_labeled.h5ad, replogle2022_k562_essential.h5ad)
# are large (~5 GB total) but re-downloadable from Figshare via notebook 03.

set -euo pipefail

FORCE=false
if [[ "${1:-}" == "--force" ]]; then
  FORCE=true
fi

DATA_DIR="$(cd "$(dirname "$0")/../data" 2>/dev/null && pwd)" || {
  echo "data/ directory not found — nothing to clean."
  exit 0
}

# Files created by notebook 03 (raw downloads) and 05–14 (derived intermediates)
FILES=(
  # Raw downloads — re-download via notebook 03 (~5 GB total)
  "$DATA_DIR/norman2019_labeled.h5ad"
  "$DATA_DIR/replogle2022_k562_essential.h5ad"
  # Derived intermediates — regenerated by running notebooks 03 and 05–14 in order
  "$DATA_DIR/norman_raw.h5ad"
  "$DATA_DIR/norman_subset.h5ad"
  "$DATA_DIR/norman_qc.h5ad"
  "$DATA_DIR/norman_assigned.h5ad"
  "$DATA_DIR/norman_processed.h5ad"
  "$DATA_DIR/norman_mixscape.h5ad"
  "$DATA_DIR/de_results.pkl"
  "$DATA_DIR/perturbation_scores.csv"
)

FOUND=()
for f in "${FILES[@]}"; do
  if [[ -e "$f" ]]; then
    FOUND+=("$f")
  fi
done

if [[ ${#FOUND[@]} -eq 0 ]]; then
  echo "Nothing to clean — no perturb_seq data files found in $DATA_DIR"
  exit 0
fi

echo "perturb_seq data files to remove:"
TOTAL=0
for f in "${FOUND[@]}"; do
  SIZE=$(du -sh "$f" 2>/dev/null | cut -f1)
  echo "  [$SIZE]  $f"
  BYTES=$(du -sk "$f" 2>/dev/null | cut -f1)
  TOTAL=$((TOTAL + BYTES))
done
echo "  Total: $(echo "$TOTAL" | awk '{printf "%.1f GB", $1/1024/1024}') would be freed"

if [[ "$FORCE" == false ]]; then
  echo ""
  echo "Dry run — no files deleted. Run with --force to delete."
  exit 0
fi

echo ""
for f in "${FOUND[@]}"; do
  rm -rf "$f"
  echo "Deleted: $f"
done
echo "Done."
